export const chapterToDataStructureCandidates: Record<string, string[]> = {
  '1.1': ['array', 'arrays'],
  '1.2': ['array', 'arrays'],
  arrays: ['array', 'arrays'],
  '2.1': ['array', 'arrays'],
  'linked-lists': ['linkedlist', 'linked-list'],
  '2.2': ['linkedlist', 'linked-list'],
  stacks: ['stack', 'linkedlist'],
  '2.3': ['stack', 'linkedlist'],
  queues: ['queue', 'linkedlist'],
  '2.4': ['queue', 'linkedlist'],

  '3.1': ['array', 'arrays'],
  '3.2': ['array', 'arrays'],
  '3.2.1': ['array', 'arrays'],
  '3.2.2': ['array', 'arrays'],
  '3.2.3': ['array', 'arrays'],

  'tree-basics': ['tree', 'binarytree'],
  '4.1': ['tree', 'binarytree'],
  'tree-traversal': ['binarytree'],
  'binary-tree-basics-traversal': ['binarytree'],
  'binary-tree-basics': ['binarytree'],
  'binary-trees': ['binarytree'],
  '4.2': ['binarytree'],
  '4.3': ['binarytree'],
  'threaded-binary-tree': ['binarytree'],
  '4.4': ['binarytree'],
  'search-trees': ['binarytree'],
  'bst-basics': ['binarytree'],
  '4.5': ['binarytree'],
  'avl-tree': ['binarytree'],
  '4.6': ['binarytree'],
  'red-black-tree': ['binarytree'],
  '4.7': ['binarytree'],
  'multiway-balanced-tree': ['binarytree'],
  '4.8': ['binarytree'],
  'huffman-trees': ['binarytree'],
  '4.9': ['binarytree'],
  heap: ['binarytree'],
  '4.10': ['binarytree'],

  'graph-basics': ['graph-fundamental', 'graph'],
  '5.1': ['graph-fundamental', 'graph'],
  'graph-traversal': ['graph-traversal', 'graph-fundamental'],
  'graph-traversal-overview': ['graph-traversal', 'graph-fundamental'],
  'graph-dfs': ['graph-traversal', 'graph-fundamental'],
  'graph-bfs': ['graph-traversal', 'graph-fundamental'],
  '5.2': ['graph-traversal', 'graph-fundamental'],
  '5.2.1': ['graph-traversal', 'graph-fundamental'],
  '5.2.2': ['graph-traversal', 'graph-fundamental'],
  '5.2.3': ['graph-traversal', 'graph-fundamental'],

  'shortest-paths': ['shortest-path', 'graph-fundamental'],
  'shortest-path-overview': ['shortest-path', 'graph-fundamental'],
  'dijkstra-algorithm': ['shortest-path', 'graph-fundamental'],
  'bellman-ford-algorithm': ['shortest-path', 'graph-fundamental'],
  'floyd-algorithm': ['shortest-path', 'graph-fundamental'],
  '5.3': ['shortest-path', 'graph-fundamental'],
  '5.3.1': ['shortest-path', 'graph-fundamental'],
  '5.3.2': ['shortest-path', 'graph-fundamental'],
  '5.3.3': ['shortest-path', 'graph-fundamental'],
  '5.3.4': ['shortest-path', 'graph-fundamental'],

  'minimum-spanning-trees': ['minimum-spanning-trees', 'graph-fundamental'],
  'mst-overview': ['minimum-spanning-trees', 'graph-fundamental'],
  'prim-algorithm': ['minimum-spanning-trees', 'graph-fundamental'],
  'kruskal-algorithm': ['minimum-spanning-trees', 'graph-fundamental'],
  '5.4': ['minimum-spanning-trees', 'graph-fundamental'],
  '5.4.1': ['minimum-spanning-trees', 'graph-fundamental'],
  '5.4.2': ['minimum-spanning-trees', 'graph-fundamental'],
  '5.4.3': ['minimum-spanning-trees', 'graph-fundamental'],

  searching: ['search', 'sequential-search', 'binary-search-algorithm', 'hash-tables'],
  '6': ['search', 'sequential-search', 'binary-search-algorithm', 'hash-tables'],
  'linear-search': ['sequential-search', 'search'],
  'binary-search': ['binary-search-algorithm', 'search'],
  'hash-tables': ['hash-tables', 'search'],
  'advanced-search': ['advanced-search-structures', 'search'],
  'b-tree-search': ['advanced-search-structures', 'search'],
  'b-plus-tree-search': ['advanced-search-structures', 'search'],
  '6.1': ['sequential-search', 'search'],
  '6.2': ['binary-search-algorithm', 'search'],
  '6.3': ['hash-tables', 'search'],
  '6.4': ['advanced-search-structures', 'search'],
  '6.5': ['advanced-search-structures', 'search'],

  sorting: ['sorting'],
  '7': ['sorting'],
  'simple-sorts': ['simple-sorting-algorithms', 'sorting'],
  'insertion-sort': ['simple-sorting-algorithms', 'sorting'],
  'bubble-sort': ['simple-sorting-algorithms', 'sorting'],
  'selection-sort': ['simple-sorting-algorithms', 'sorting'],
  'advanced-sorts': ['advanced-sorting-algorithms', 'sorting'],
  'shell-sort': ['advanced-sorting-algorithms', 'sorting'],
  'quick-sort': ['advanced-sorting-algorithms', 'sorting'],
  'merge-sort': ['advanced-sorting-algorithms', 'sorting'],
  'heap-sort': ['advanced-sorting-algorithms', 'sorting'],
  'special-sorts': ['special-sorting-methods', 'sorting'],
  'radix-sort': ['special-sorting-methods', 'sorting'],
  'bucket-sort': ['special-sorting-methods', 'sorting'],
  'external-sort': ['special-sorting-methods', 'sorting'],
  'sorting-analysis': ['sorting-algorithm-analysis', 'sorting'],
  '7.1': ['simple-sorting-algorithms', 'sorting'],
  '7.2': ['simple-sorting-algorithms', 'sorting'],
  '7.3': ['simple-sorting-algorithms', 'sorting'],
  '7.4': ['advanced-sorting-algorithms', 'sorting'],
  '7.5': ['advanced-sorting-algorithms', 'sorting'],
  '7.6': ['advanced-sorting-algorithms', 'sorting'],
  '7.7': ['advanced-sorting-algorithms', 'sorting'],
  '7.8': ['special-sorting-methods', 'sorting'],
  '7.9': ['special-sorting-methods', 'sorting'],
  '7.10': ['special-sorting-methods', 'sorting'],
  '7.11': ['sorting-algorithm-analysis', 'sorting']
};

export const getDataStructureCandidateIds = (chapterId: string, fallback: string[] = [chapterId]): string[] => {
  return chapterToDataStructureCandidates[chapterId] ?? fallback;
};
